# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # In diesem Abschnitt können Umgebungsvariablen definiert werden
  db01 = "192.168.120.10"
  fe01 = "192.168.120.11"
  dbPassword = "oB7ainoghae4eelah1"
  serverName = "seafilesrv"
  seafileAdmin = "email@email.com"
  serviceURL = "localhost"

  # Fest programmierte Werte:
  # db user für seafile: seafile
  # Datenbanknamen: seafiledb seahubdb ccnetdb

  # Konfigurationsabschnitt
  config.vm.define "db01" do |db|
    db.vm.box = "centos/7"
	  db.vm.provider "virtualbox" do |vb|
	    vb.memory = "512"  
	  end
    db.vm.hostname = "db01"
    # db.vm.synced_folder ".", "/vagrant"
    db.vm.network "private_network", ip: db01
    db.vm.provision "shell", inline: "echo 'export db01=#{db01}\nexport fe01=#{fe01}' > /etc/profile.d/hostips.sh"
    db.vm.provision "shell", inline: "echo 'export dbPassword=#{dbPassword}' > /etc/profile.d/passwd.sh"
    db.vm.provision "shell", path: "db.sh"
  end
  config.vm.define "fe01" do |fe|
    fe.vm.box = "centos/7"
	  fe.vm.provider "virtualbox" do |vb|
	    vb.memory = "512"  
    end
    fe.vm.hostname = "fe01"
    # fe.vm.synced_folder ".", "/vagrant"
    fe.vm.network "private_network", ip: fe01
    fe.vm.network "forwarded_port", guest: 80, host: 80
    fe.vm.network "forwarded_port", guest: 443, host: 443
    fe.vm.provision "shell", inline: "echo 'export db01=#{db01}\nexport fe01=#{fe01}\nexport serverName=#{serverName} export serviceURL=#{serviceURL}' > /etc/profile.d/hostips.sh"
    fe.vm.provision "shell", inline: "echo 'export dbPassword=#{dbPassword}\nexport seafileAdmin=#{seafileAdmin}' > /etc/profile.d/passwd.sh"
    fe.vm.provision "shell", path: "seafile.sh"
  end
end
