# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # In diesem Abschnitt können Umgebungsvariablen definiert werden
  db01 = "192.168.120.10"
  fe01 = "192.168.120.11"
  dbPassword = "seafile"

  # Fest programmierte Werte:
  # db user für seafile: seafile
  # Datenbanknamen: seafiledb seahubdb ccnetdb

  # Konfigurationsabschnitt
  config.vm.define "db01" do |db|
    db.vm.box = "centos/7"
	  db.vm.provider "virtualbox" do |vb|
	    vb.memory = "512"  
	  end
    db.vm.hostname = "db01"
    # db.vm.synced_folder ".", "/vagrant"
    db.vm.network "private_network", ip: db01
    db.vm.provision "shell", path: "db.sh"
    db.vm.provision "shell", inline: "echo 'export db01=#{db01}\nexport fe01=#{fe01}' > /etc/profile.d/hostips.sh"
    db.vm.provision "shell", inline: "echo 'export dbPassword=#{dbPassword}' > /etc/profile.d/db-passwd.sh"
  end
  config.vm.define "fe01" do |fe|
    fe.vm.box = "centos/7"
	  fe.vm.provider "virtualbox" do |vb|
	    vb.memory = "512"  
    end
    fe.vm.hostname = "fe01"
    # fe.vm.synced_folder ".", "/vagrant"
    fe.vm.network "private_network", ip: fe01
  	fe.vm.provision "shell", path: "seafile.sh"
    fe.vm.provision "shell", inline: "echo 'export db01=#{db01}\nexport fe01=#{fe01}' > /etc/profile.d/hostips.sh"
    fe.vm.provision "shell", inline: "echo 'export dbPassword=#{dbPassword}' > /etc/profile.d/db-passwd.sh"
  end
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://proxy.corproot.net:8079/"
    config.proxy.https    = "http://proxy.corproot.net:8079/"
    config.proxy.no_proxy = "localhost,127.0.0.1"
  end
end
