---
version: '3.6'

services:
  traefik:
    image: traefik:latest
    restart: always
    volumes:
      - $PWD/config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse_proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

networks:
  reverse_proxy:
    external: 
      name: reverse_proxy
