---
version: '3.7'

services:
  wordpress_db:
    image: mysql:5.7
    volumes: 
      - wordpress_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  
  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    labels:
      - "traefik.backend=wordpress"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:wordpress.tbz.lan"
      - "traefik.port=80"
      - "traefik.docker.network=reverse_proxy"

volumes:
  wordpress_db_data: {}